### ISSUE TITLE
Error decoding/generating precomp file in latest branch

### ISSUE THREAD

**Issue by gballet** [gballet/go-ethereum#186]
This happens in `cache-point-in-access-witness` after merging https://github.com/gballet/go-ethereum/pull/184.

Using a precomp file from `master`, it will cause the following stack trace. The same stack trace will happen when starting with a missing file.

```
--- FAIL: TestReproduceTree (0.07s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 76409 [running]:
testing.tRunner.func1.2({0x6616a0, 0x708f40})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x6616a0, 0x708f40})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/crate-crypto/go-ipa/banderwagon.(*LagrangeTablePoints).Deserialize(0xc0002f2060, {0x7096e0, 0xc000702000})
	/home/gballet/go/pkg/mod/github.com/crate-crypto/go-ipa@v0.0.0-20230315201338-1643fdc2ead8/banderwagon/precomp_multiexp.go:258 +0x19d
github.com/crate-crypto/go-ipa/banderwagon.DeserializePrecomputedLagrange({0x7096e0, 0xc000702000})
	/home/gballet/go/pkg/mod/github.com/crate-crypto/go-ipa@v0.0.0-20230315201338-1643fdc2ead8/banderwagon/precomp_multiexp.go:152 +0x1c5
github.com/crate-crypto/go-ipa/ipa.DeserializeSRSPrecomp({0xc004e70000, 0x7f84018, 0x7f84019})
	/home/gballet/go/pkg/mod/github.com/crate-crypto/go-ipa@v0.0.0-20230315201338-1643fdc2ead8/ipa/srs_precomp.go:73 +0x1a6
github.com/gballet/go-verkle.GetConfig()
	/home/gballet/go/pkg/mod/github.com/gballet/go-verkle@v0.0.0-20230317174103-141354da6b11/config_ipa.go:61 +0x95
github.com/gballet/go-verkle.NewLeafNode({0xc0003cce00, 0x1f?, 0x40}, {0xc000647800, 0x100, 0x100})
	/home/gballet/go/pkg/mod/github.com/gballet/go-verkle@v0.0.0-20230317174103-141354da6b11/tree.go:218 +0x1dc
github.com/gballet/go-verkle.(*InternalNode).InsertStem(0xc0006af800, {0xc0003cce00, 0x1f, 0x40}, {0xc000647800, 0x100, 0x100}, 0x0)
	/home/gballet/go/pkg/mod/github.com/gballet/go-verkle@v0.0.0-20230317174103-141354da6b11/tree.go:291 +0x11e
github.com/gballet/go-verkle.(*InternalNode).Insert(0x6acc84?, {0xc0003cce00, 0x20, 0x40}, {0xc0003cd1c0, 0x20, 0x40}, 0x41c591?)
	/home/gballet/go/pkg/mod/github.com/gballet/go-verkle@v0.0.0-20230317174103-141354da6b11/tree.go:282 +0xdc
github.com/ethereum/go-ethereum/trie.TestReproduceTree(0xc0003c4820)
	/home/gballet/src/go-ethereum/trie/verkle_test.go:71 +0xd4b
testing.tRunner(0xc0003c4820, 0x6c5ac0)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/ethereum/go-ethereum/trie	46.549s
FAIL
```

Command to reproduce:

```
$ go test ./trie
```

**Comment by jsign** [comment]
This test doesn't fail locally (with or without a precomp file).

Looking in our CI, I noticed we're [still downloading old precomp there](https://github.com/gballet/go-ethereum/actions/runs/4465144554/workflow#L46).

Created https://github.com/gballet/go-ethereum/pull/187 to update and we can see if now CI is happy.

**Comment by gballet** [comment]
Solved, thanks @jsign
